### ISSUE TITLE
capture and report DenovoAssemblyError at trinity step

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#18] opened 2016-06-16 21:41 UTC
We recently introduced a DenovoAssemblyError in the assemble_trinity step that makes trinity failures more interpretable. Similar to what is done for [PoorAssemblyError currently](https://github.com/dnanexus/viral-ngs/blob/dnanexus/viral-ngs-assembly-scaffolding/src/code.sh#L33), can this error be captured and logged in a more user friendly way? This would then obviate the need for the [min-base-count check](https://github.com/dnanexus/viral-ngs/blob/dnanexus/viral-ngs-trinity/src/viral-ngs-trinity.sh#L19) that currently happens prior to Trinity, so maybe we can remove that, now that a more informative error is being captured instead?

**Comment by yifei-men** [comment] 2016-06-20 17:17
This should be addressed by https://github.com/dnanexus/viral-ngs/commit/478b823faf1d1d96df472f9eb6b7558f2e2ac52f (awaiting CI tests)

But knowing my knack for typos, is there any easy-to-reproduce dataset that we can use to trigger this error and see that it's captured accurately? I see that it's tested [in your own CI tests](https://github.com/broadinstitute/viral-ngs/blob/a46f204e9ec7dc6a33fc170e89352daeaee7ca19/test/unit/test_assembly.py#L65). Does this basically involve passing an empty bam file as input?

cc @tomkinsc

**Comment by dpark01** [comment] 2016-06-20 17:25
Passing an empty bam file as input should reproducibly create that error!

**Comment by yifei-men** [comment] 2016-06-20 17:27
👍 awesome, thanks Danny

**Comment by yifei-men** [comment] 2016-06-20 23:00
Manually validated in [this job](https://platform.dnanexus.com/projects/BXBXK180x0z7x5kxq11p886f/monitor/job/BxZ6kj80x0z37kxzZJzbY0bb)

The error email looks like this:
<img width="561" alt="screen shot 2016-06-20 at 3 59 55 pm" src="https://cloud.githubusercontent.com/assets/13123683/16212921/1c43f4c8-3700-11e6-8f7d-0fcd359e13d1.png">

This seems a little ungrammatical... I'll change the verbiage to "detailed logs."

**Comment by yifei-men** [comment] 2016-06-21 17:29
Addressed by #20

**Closed as completed by yifei-men** 2016-06-21 17:29 UTC
